config/routes.rb
EmployeeTimeLog::Application.routes.draw do
  resources :employees do
    resources :datelogs do
      resources :timelogs
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to=> 'employees#new'
  match '/signin',  :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete

  match '/help',    :to=> 'home#help'
  match '/about',   :to=> 'home#about'
  match '/contact', :to=> 'home#contact'

  get "home/index"

   root :to => 'home#index'

end

app/models/datelog.rb
# == Schema Information
#
# Table name: datelogs
#
#  id          :integer          not null, primary key
#  daylog      :date
#  tottime     :integer
#  altnumeric  :integer
#  employee_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Datelog < ActiveRecord::Base
  belongs_to :employee
  has_many :timelogs, :dependent=>:destroy
  attr_accessible :altnumeric, :daylog, :tottime
  validates :daylog, :presence => true
  
  accepts_nested_attributes_for :timelogs, :allow_destroy => true
end

app/controllers/datelogs_controller.rb
class DatelogsController < ApplicationController

  def new
    @employee = Employee.find(params[:employee_id])
    @datelog = @employee.datelogs.new(params[:datelog])
    respond_to do |format|
      if @datelog.save
        format.html { redirect_to employee_datelog_path(@employee, @datelog), :notice => 'Datelog was successfully created.' }
        format.json { render :json => @datelog, :status => :created, :location => @datelog }
      else
        format.html { render :action => "new" }
        format.json { render :json => @datelog.errors, :status => :unprocessable_entity }
      end
    end
  end

  def create
    @employee = Employee.find(params[:employee_id])
    @datelog = @employee.datelogs.new(params[:datelog])
    respond_to do |format|
      if @datelog.save
        format.html { redirect_to employee_datelog_path(@employee, @datelog), :notice => 'Datelog was successfully created.' }
        format.json { render :json => @datelog, :status => :created, :location => @datelog }
      else
        format.html { render :action => "new" }
        format.json { render :json => @datelog.errors, :status => :unprocessable_entity }
      end
    end
  end

  def index
    @employee = Employee.find(params[:employee_id])
    @datelogs = @employee.datelogs.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @datelogs }
    end
  end

  def show
    @datelog = Datelog.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @datelog }
    end
  end
  def edit
    @datelog = Datelog.find(params[:id])
  end

  def update
    @datelog = Datelog.find(params[:id])
    respond_to do |format|
      if @datelog.update_attributes(params[:datelog])
        format.html { redirect_to employee_datelogs_path(@datelog.employee_id), :notice => 'Datelog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @datelog.errors, :status => :unprocessable_entity }
      end
    end
  end

 def destroy
    @employee = Employee.find(params[:employee_id])
    @datelog = Datelog.find(params[:id])
    @datelog.destroy
    redirect_to employee_path(@employee)
 end
   
end

app/helpers/datelogs_helper.rb
module DatelogsHelper
end

app/views/datelogs/_datelog.html.haml
%p
  %b Date:
  = datelog.daylog
%p
  %b Time logged:
  = datelog.timelogs.sum('hourlog')
%p
  = link_to 'Remove Date',[datelog.employee, datelog], :confirm => 'Are you sure?', :method => :delete

app/views/datelogs/_form.html.haml
= form_for([:employee, @datelog]) do |f|
  - if @datelog.errors.any?
    %div{:id=>"error_explanation"}
      %h2
        = pluralize(@datelog.errors.count, "error")
        prohibited this datelog from being saved:
      %ul
        - @datelog.errors.full_messages.each do |msg|
          %li= msg
  %div.dateformat
    = f.label :daylog, "Date"
    %br/
    = f.date_select :daylog, :size=>"25x25"
  %h2 Timelogs
  = render @datelog.timelogs
  - if @datelog.persisted?
    = link_to 'Add Timelog', new_employee_datelog_timelog_url(@datelog.employee, @datelog)
  %div.actions
    = f.submit

app/views/datelogs/edit.html.haml
= form_for([:employee, @datelog]) do |f|
  - if @datelog.errors.any?
    %div{:id=>"error_explanation"}
      %h2
        = pluralize(@datelog.errors.count, "error")
        prohibited this datelog from being saved:
      %ul
        - @datelog.errors.full_messages.each do |msg|
          %li= msg
  %div{:class=>"datelabels"}
    = f.label :daylog, "Date"
    %br/
    = f.date_select :daylog
  %div{:class=>"timeformat"}
    %h2.timeformat
      Timelogs
    = render @datelog.timelogs
    %br/
    %br/
    %div{:class=>"timeformat"}
      - if @datelog.persisted?
        = link_to 'Add Timelog', new_employee_datelog_timelog_url(@datelog.employee, @datelog)
  %br/
  %br/
  %div{:class=>"actions"}
    = f.submit
= link_to 'Show', employee_datelogs_path(@datelog.employee, @datelog)
%br/
= link_to 'Back', employee_datelogs_path(@datelog.employee)

app/views/datelogs/index.html.haml
%h1 Listing datelogs
- @datelogs.each do |datelog|
  %div.timelogstyle
    %h2= datelog.daylog
    Timelogs: 
    %table
      %colgroup
        %col{:width=>"75"}
        %col{:width=>"50"}
        %col{:width=>"200"}
      %tr
        %th Type
        %th Hours
        %th Description
    %p= render datelog.timelogs
    = link_to 'Add to/Edit Datelog', edit_employee_datelog_path(@employee, datelog)
%div
  = link_to 'Back to Employee', employee_path(@employee)

app/views/datelogs/new.html.haml
%h1 New Datelog
= form_for([:employee, @datelog]) do |f|
  - if @datelog.errors.any?
    %div{:id=>"error_explanation"}
      %h2
        = pluralize(@datelog.errors.count, "error")
        prohibited this datelog from being saved:
      %ul
        - @datelog.errors.full_messages.each do |msg|
          %li= msg
  %div.dateformat
    = f.label :daylog, "Date"
    %br/
    = f.date_select :daylog, :size=>"25x25"
  %h2 Timelogs
  = render @datelog.timelogs
  - if @datelog.persisted?
    = link_to 'Add Timelog', new_employee_datelog_timelog_url(@datelog.employee, @datelog)
  %div.actions
    = f.submit
= link_to 'Back', employee_path(@employee)

app/views/datelogs/show.html.haml
%h1= @datelog.daylog
%h2
  Time Logged by Date
  %br/
  (Total Hours:
  = @datelog.timelogs.sum('hourlog')
  )
%table
  %colgroup
    %COL{:width=>"100"}
    %COL{:width=>"75"}
    %COL{:width=>"300"}
  %tr
    %th Type
    %th Hours
    %th Description
= render @datelog.timelogs
%br/
%div.timeformat
  = link_to 'Add Timelog', new_employee_datelog_timelog_url(@datelog.employee, @datelog)
%br/
%br/
= link_to 'Back', employee_datelogs_path