config/routes.rb
EmployeeTimeLog::Application.routes.draw do
  resources :employees do
    resources :datelogs do
      resources :timelogs
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to=> 'employees#new'
  match '/signin',  :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete

  match '/help',    :to=> 'home#help'
  match '/about',   :to=> 'home#about'
  match '/contact', :to=> 'home#contact'

  get "home/index"

   root :to => 'home#index'

end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  title       :string(255)
#  code        :string(255)
#  tottime     :integer
#  altid       :integer
#  division_id :integer
#  creation    :datetime
#  admin       :binary
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Employee < ActiveRecord::Base
  attr_accessible :admin, :altid, :creation, :division_id, :name, :title, :password, :tottime, :email, :password_confirmation
has_secure_password

before_save { |employee| employee.email = email.downcase }
before_save :create_remember_token

  validates :altid, :presence => true,
                    :length => { :maximum => 5 } 
  validates :name, :presence => true
  validates :title, :presence => true
  validates :password, :presence=> true, :length=> { :minimum=> 6 }
  validates :password_confirmation, :presence=> true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence=> true, :format=>{:with=> VALID_EMAIL_REGEX}

  has_many :datelogs, :dependent => :destroy
  has_many :timelogs, :through => :datelogs

  accepts_nested_attributes_for :datelogs, :allow_destroy => true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json

  before_filter :signed_in_employee, :only=>[:index, :edit, :update, :destroy]
  before_filter :correct_employee, :only=> [:edit, :update]
  before_filter :admin_employee, :only=> :destroy

  def index
    @employees = Employee.all
      respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])
    respond_to do |format|
      if @employee.save
        sign_in @employee
        flash[:success] = "Welcome back!"
        format.html { redirect_to @employee, :notice => 'Employee was successfully created.' }
        format.json { render :json => @employee, :status => :created, :location => @employee }
      else
        format.html { render :action => "new" }
        format.json { render :json => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        sign_in @employee
        format.html { redirect_to @employee, :notice => 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  private

    def signed_in_employee
      unless signed_in?
        store_location
        redirect_to signin_url, :notice=> "Please sign in."
      end
    end

    def correct_employee
      @employee = Employee.find(params[:id])
      redirect_to(root_path) unless current_employee?(@employee)
    end

    def admin_employee
      redirect_to(root_path) unless current_employee.admin?
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  # Returns the Gravatar (http://gravatar.com/) for the given employee.
  def gravatar_for(employee, options = {:size=>50})
    gravatar_id = Digest::MD5::hexdigest(employee.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, :alt=> employee.name, :class=> "gravatar")
  end

end

app/views/employees/edit.html.haml
- provide(:title, "Edit Employee")
%h1 Editing employee
%div.row
  %div.span6.offset3
    = form_for(@employee) do |f|
      = render 'shared/error_messages'
      = f.label :name
      = f.text_field :name
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation, "Confirm Password"
      = f.password_field :password_confirmation
      = f.submit "Save changes", :class=> "btn btn-large btn-primary"

%li= link_to 'Show', @employee
%li= link_to 'Back', employees_path

app/views/employees/index.html.haml
- provide(:title, 'All employees')
%h1 Listing employees
%br/
%ul.employees
  - @employees.each do |employee|
    %li= link_to employee.name, employee
%br/
%table{:style=>"background-color:#FFD700"}
  %tr
    %th{:align=>"left"} Name
    %th{:align=>"left"} Title
    %th
    %th{:align=>"left"} Tot Time
    %th
    %th{:align=>"left"} Altid
    %th{:align=>"left"} Division
    %th{:align=>"left"} Admin
    %th
    %th
    %th
  %COLGROUP
    %COL{:width=>"100"}
    %COL{:width=>"50"}
    %COL{:width=>"25"}
    %COL{:width=>"40"}
    %COL{:width=>"25"}
    %COL{:width=>"50"}
    %COL{:width=>"100"}
    %COL{:width=>"50"}
    %COL{:width=>"75"}
    %COL{:width=>"100"}
    %COL{:width=>"200"}
    - @employees.each do |employee|
      %tr.employees
        %td
          %li= link_to employee.name, employee
        %td= employee.title
        %td
        %td= employee.timelogs.sum('hourlog')
        %td
        %td= employee.altid
        %td= employee.division_id
        %td= employee.admin
        %td= link_to 'Log Time', employee
        %td= link_to 'Edit Employee', edit_employee_path(employee)
        %td= link_to 'Remove Employee Record', employee, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br/
%li= link_to 'Add a New Employee', new_employee_path

app/views/employees/new.html.haml
- provide(:title, 'Sign up')
%h1 New employee creation
%div.row
  %div.span6.offset3
    = form_for(@employee) do |f|
      = render 'shared/error_messages'
      = f.label :name
      = f.text_field :name
      = f.label :title
      = f.text_field :title
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation
      = f.label :altid
      = f.number_field :altid
      = f.label :division_id
      = f.number_field :division_id
      = f.label :email
      = f.text_field :email
      = f.label :admin
      = f.check_box(:admin, :size=>5)
      %br/
      %br/
      = f.submit "Create User Record", :class=> "btn btn-large btn-primary"
%li= link_to 'Back', employees_path

app/views/employees/show.html.haml
- provide(:title, @employee.name)
%div{:class=>"row"}
  %aside.span4
    %section
      %h1= @employee.name
%p{:id=>"notice"}
  = notice
%table.erictable
  %tr
    %th Name
    %th Title
    %th
    %th Total Time
    %th
    %th Altid
    %th Division
    %th Admin
    %th
  %COLGROUP
    %COL{:width=>"100"}
    %COL{:width=>"50"}
    %COL{:width=>"25"}
    %COL{:width=>"40"}
    %COL{:width=>"25"}
    %COL{:width=>"50"}
    %COL{:width=>"100"}
    %COL{:width=>"75"}
    %COL{:width=>"100"}
  %tr
    %td= @employee.name
    %td= @employee.title
    %td
    %td= @employee.tottime
    %td
    %td= @employee.altid
    %td= @employee.division_id
    %td= @employee.admin
    %td= link_to 'Edit Employee', edit_employee_path(@employee)
%br/
%br/
%h2 Time Logged by Date
= render @employee.datelogs
= link_to 'Add New Datelog', new_employee_datelog_path(@employee,@datelog)
%br/
= link_to 'View Datelog Index', employee_datelogs_path(@employee,@datelog)
= link_to 'Edit', edit_employee_path(@employee)
= link_to 'Back', employees_path