config/routes.rb
EmployeeTimeLog::Application.routes.draw do
  resources :employees do
    resources :datelogs do
      resources :timelogs
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to=> 'employees#new'
  match '/signin',  :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete

  match '/help',    :to=> 'home#help'
  match '/about',   :to=> 'home#about'
  match '/contact', :to=> 'home#contact'

  get "home/index"

   root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def help
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
- provide(:title, 'About Us')
%h1 About Us
%p.ericclass
  This application lets different employees log time for work using a number of different activity types by date and employee. It will calculate total time per day so that it can be easily evaluated. See the repo at 
  %a{:href=>"https://github.com/eejones/Employee_time_log"}Employee Time Log Repo

app/views/home/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact
%p.ericclass
  Contact Eric Jones about your issues with this timelog - 
  %a{:href=>"https://github.com/eejones"} Contact Eric

app/views/home/help.html.haml
- provide(:title, 'Help')
%h1 Help
%p.ericclass
  Good luck getting help, but you can look for details on this app at Eric's github -
  %a{:href=>"https://github.com/eejones", :class=>"ericcolor"} Github account for Eric Jones

app/views/home/index.html.haml
%div{:class=>"page-header"}
  %h1 Logging Time
  %h2
    This is the home page for logging time
    %a{:href=>"https://github.com/eejones/Employee_time_log" }Employee Time Log
    Eric E Jones
    = link_to "Sign up now!", signup_path, :class=> "btn btn-large btn-primary"
%br/
= link_to image_tag("genericcompany.png", :alt=> "Rails"), 'http://en.wikipedia.org/wiki/Business_opportunity'
%br/
= link_to "Employee Time Entry", employees_path