config/routes.rb
EmployeeTimeLog::Application.routes.draw do
  resources :employees do
    resources :datelogs do
      resources :timelogs
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to=> 'employees#new'
  match '/signin',  :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete

  match '/help',    :to=> 'home#help'
  match '/about',   :to=> 'home#about'
  match '/contact', :to=> 'home#contact'

  get "home/index"

   root :to => 'home#index'

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{:href=>"http://en.wikipedia.org/wiki/Timesheet"} Timesheets
    by Eric E Jones
  %nav
    %ul
      %li= link_to "Help", help_path
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li
        %a{:href=>"http://en.wikipedia.org/wiki/Time_tracking_software"} Time Tracking Software

app/views/layouts/_header.html.haml
%header{:class=>"navbar navbar-fixed-top navbar-inverse"}
  %div.navbar-inner
    %div.container
      - if signed_in?
        = link_to(@current_employee.name, current_employee, {:id=> "logo"})
      - else
        = link_to("Employee Log", root_path, {:id=> "logo"})
      %nav
        %ul{:class=>"nav pull-right"}
          %li= link_to "Home", root_path
          %li= link_to "Help", help_path
          - if signed_in?
            %li= link_to "Employee Listing", employees_path
            %li{:id=>"fat-menu", :class=>"dropdown"}
              %a{:href=>"#", :class=>"dropdown-toggle", "data-toggle"=>"dropdown"}
                %strong
                  Employee
                %b{:class=>"caret"}  
              %ul{:class=>"dropdown-menu"}
                %li= link_to "Log Time", current_employee
                %li= link_to "Settings", edit_employee_path(current_employee)
                %li{:class=>"divider"}
                %li= link_to "Sign out", signout_path, :method=> "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/application.html.haml
!!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    %div.container
      - flash.each do |key, value|
        %div{:class=>"alert alert-<%= key %>"}
          = value
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?